### ISSUE TITLE
NoClassDefFound on guava class

### ISSUE THREAD

**Issue by shenberg** [scijava/jython-shaded#4]
I'm getting a new error after an upgrade from 2.7.0 to 2.7.1 - the same code worked perfectly using jython-shaded 2.7.0.
The code is running `re.sub('(.)([A-Z][a-z]+)', r'\1_\2', some_string)`

    Traceback (most recent call last):
      File "main", line 149, in transform
      File "/opt/tomcat/webapps/ROOT/WEB-INF/lib/jython-shaded-2.7.1.jar/Lib/re.py", line 151, in sub
    java.lang.NoClassDefFoundError: Could not initialize class org.python.google.common.util.concurrent.SettableFuture
    	at org.python.google.common.cache.LocalCache$LoadingValueReference.&lt;init&gt;(LocalCache.java:3570)
    	at org.python.google.common.cache.LocalCache$LoadingValueReference.&lt;init&gt;(LocalCache.java:3574)
    	at org.python.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2273)
    	at org.python.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
    	at org.python.google.common.cache.LocalCache.get(LocalCache.java:4053)
    	at org.python.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
    	at org.python.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
    	at org.python.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
    	at org.python.modules.sre.SRE_STATE$CACHE.get(SRE_STATE.java:1290)
    	at org.python.modules.sre.SRE_STATE$CACHE.access$000(SRE_STATE.java:1253)
    	at org.python.modules.sre.SRE_STATE.&lt;init&gt;(SRE_STATE.java:1295)
    	at org.python.modules.sre.PatternObject.subx(PatternObject.java:152)
    	at org.python.modules.sre.PatternObject.sub(PatternObject.java:113)
    	at org.python.modules.sre.PatternObject$sub_exposer.__call__(Unknown Source)
    	at org.python.core.PyObject.__call__(PyObject.java:515)
    	at org.python.core.PyObject.__call__(PyObject.java:519)
    	at re$py.sub$3(/opt/tomcat/webapps/ROOT/WEB-INF/lib/jython-shaded-2.7.1.jar/Lib/re.py:151)
    	at re$py.call_function(/opt/tomcat/webapps/ROOT/WEB-INF/lib/jython-shaded-2.7.1.jar/Lib/re.py)
    	at org.python.core.PyTableCode.call(PyTableCode.java:171)
    	at org.python.core.PyBaseCode.call(PyBaseCode.java:154)
    	at org.python.core.PyFunction.__call__(PyFunction.java:423)
    	at main$py.transform$9(main:161)
    	at main$py.call_function(main)
    	at org.python.core.PyTableCode.call(PyTableCode.java:171)
    	at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
    	at org.python.core.PyFunction.__call__(PyFunction.java:413)
    	at org.python.pycode._pyx18.f$0(transform_func:1)
    	at org.python.pycode._pyx18.call_function(transform_func)
    	at org.python.core.PyTableCode.call(PyTableCode.java:171)
    	at org.python.core.PyCode.call(PyCode.java:18)
    	at org.python.core.Py.runCode(Py.java:1614)
    	at org.python.core.Py.exec(Py.java:1658)
    <snip>
    	at java.lang.Thread.run(Thread.java:748)
    java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: Could not initialize class org.python.google.common.util.concurrent.SettableFuture

To my layman's eyes, this looks like a version conflict of the sort we used to have and that jython-shaded solved. Also, in a different environment (apache storm) where we're forced to create a fat-jar including the jython-shaded jar, everything works a-ok.

I did some sanity-testing - the .class file is there and there's no other jython jar around.

    root@some-docker:/opt/tomcat/webapps/ROOT/WEB-INF/lib# find / -name '*jython*'
    /opt/tomcat/webapps/ROOT/WEB-INF/lib/jython-shaded-2.7.1.jar
    root@some-docker:/opt/tomcat/webapps/ROOT/WEB-INF/lib# unzip -l jython-shaded-2.7.1.jar | grep SettableF
     2062  2017-07-03 09:01   org/python/google/common/util/concurrent/SettableFuture.class`

The next thing I did is to see whether SRE_STATE's implementation changed, but the only change in the offending file between Jython 2.7.0 and 2.7.1 is very minor and not related to this error, rather to correctly dealing with 0-length matches:

https://github.com/jythontools/jython/commit/3c4f8c3c85320eb11d04edfb819c2c83c75f38bd#diff-0ec52fefe5b668dd5274b203c8f617a3

**Comment by ctrueden** [comment]
@shenberg Can you describe your runtime environment in more detail? Or better yet, offer an [MCVE](https://stackoverflow.com/help/mcve). I was not able to reproduce this problem:
```
$ mvn dependency:get -Dartifact="org.scijava:jython-shaded:2.7.0"
$ java -cp ~/.m2/repository/org/scijava/jython-shaded/2.7.0/jython-shaded-2.7.0.jar org.python.util.jython                                             #  0 {2017-09-13 13:10:37}
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_144
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> some_string = "Hello There"
>>> print re.sub('(.)([A-Z][a-z]+)', r'\1_\2', some_string)
Hello _There
>>> %
$ mvn dependency:get -Dartifact="org.scijava:jython-shaded:2.7.1"
java -cp ~/.m2/repository/org/scijava/jython-shaded/2.7.1/jython-shaded-2.7.1.jar org.python.util.jython                                             #  0 {2017-09-13 13:10:59}
Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_144
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> some_string = "Hello There"
>>> print re.sub('(.)([A-Z][a-z]+)', r'\1_\2', some_string)
Hello _There
>>> %
```

**Comment by shenberg** [comment]
Ok, the issue was related to new features in guava interacting poorly with our security manager. Specifically, guava now reads a system property on init of AbstractFuture (this happened somewhere along the line between version 18 and version 22, as verified by looking in their git repo). Worked around this in our code. Sorry for bothering you - the issue was caused by a change but by its interaction with our code.

Reference: 

Version 22.0 (Jython 2.7.1) has a System.getProperty() call on static init:
https://github.com/google/guava/blob/v22.0/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L69

Version 18.0 (Jython 2.7.0) has no such thing:
https://github.com/google/guava/blob/v18.0/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L65

**Comment by ctrueden** [comment]
Thanks for circling back. Glad you got it figured out!
